name: chord_result_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_guitar_chord: ^0.0.2
  guitar_chord_library: ^0.0.4
  just_audio: ^0.9.42

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/김건모-서울의 달/
    - assets/김동률-감사/
    - assets/비비-밤양갱/
    - assets/실리카겔-TikTakTok/
    - assets/악뮤-Give Love/
    - assets/Green Day-21 Guns/
    - assets/Green Day-Basket Case/
    - assets/Jamiroquai-Virtual Insanity/
    - assets/Woodz-Drowning/
